#!/usr/bin/env bash
set -euo pipefail

INTERACTIVE=false
[[ "${1:-}" == "-i" || "${1:-}" == "i" ]] && INTERACTIVE=true

if [ -f .env ]; then
    read -rp ".env already exists. Overwrite? [y/N] " confirm
    [[ "${confirm,,}" == "y" ]] || { echo "Aborted."; exit 0; }
fi

SESSION_SECRET=$(openssl rand -base64 32 | tr -d '\n')

if $INTERACTIVE; then
    echo ""
    read -rp "Domain (e.g. mcp.example.com): "          MCP_DOMAIN
    read -rp "GitHub Client ID: "                        GITHUB_CLIENT_ID
    read -rp "GitHub Client Secret: "                    GITHUB_CLIENT_SECRET
    read -rp "GitHub username(s) [comma-separated]: "    GITHUB_ALLOWED_USERS
    read -rp "Admin identities, prefixed e.g. github:octocat [comma-separated, optional]: " ADMIN_USERS
    read -rp "Steam Web API key [optional, leave empty to skip Steam login]: " STEAM_API_KEY
    read -rp "Steam allowed SteamID64(s) [comma-separated, optional]: " STEAM_ALLOWED_USERS
    read -rp "Log level [INFO]: "                        LOG_LEVEL_INPUT
    LOG_LEVEL="${LOG_LEVEL_INPUT:-INFO}"
    echo ""
else
    MCP_DOMAIN="CHANGE_ME"
    GITHUB_CLIENT_ID="CHANGE_ME"
    GITHUB_CLIENT_SECRET="CHANGE_ME"
    GITHUB_ALLOWED_USERS="CHANGE_ME"
    ADMIN_USERS=""
    STEAM_API_KEY=""
    STEAM_ALLOWED_USERS=""
    LOG_LEVEL="INFO"
fi

cat > .env << ENVEOF
# Generated by 'just init-env' — do not commit this file.

# ── Domain ────────────────────────────────────────────────────────────────────
# Production:  public hostname exposed by Traefik/Coolify
# Local test:  set to "localhost"
MCP_DOMAIN=${MCP_DOMAIN}

# ── Secret keys (auto-generated) ─────────────────────────────────────────────
# Signing key for admin session cookies.
SESSION_SECRET=${SESSION_SECRET}

# ── GitHub OAuth ──────────────────────────────────────────────────────────────
# Register at: https://github.com/settings/developers → OAuth Apps → New
# Homepage URL:              https://${MCP_DOMAIN}
# Authorization callback URL: https://${MCP_DOMAIN}/oauth/callback
#   (shared by admin browser login and MCP client OAuth flow)
GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}

# Comma-separated list of allowed GitHub usernames. Do NOT leave empty.
GITHUB_ALLOWED_USERS=${GITHUB_ALLOWED_USERS}

# Comma-separated list of identities with admin rights (see and manage
# every server, override visibility). Optional — leave empty for no admins.
# Values must be prefixed: "github:octocat" or "steam:76561198012345678".
ADMIN_USERS=${ADMIN_USERS}

# ── Steam login (optional alternative to GitHub) ────────────────────────────
# Get a free key at: https://steamcommunity.com/dev/apikey
STEAM_API_KEY=${STEAM_API_KEY}
STEAM_ALLOWED_USERS=${STEAM_ALLOWED_USERS}

# ── Optional ──────────────────────────────────────────────────────────────────
LOG_LEVEL=${LOG_LEVEL}
ENVEOF

echo ".env created."
$INTERACTIVE || echo "Remember to fill in the CHANGE_ME values before starting."
